import { z } from 'zod';
import { ok } from '../../lib/envelope.js';
import { notFound } from '../../lib/errors.js';
import type { OrderRow } from '../../types/db.js';
import type { ToolDefinition } from '../../types/tools.js';
import { SERVICE_TYPES } from '../../types/statuses.js';

const InputSchema = z.object({
  restaurant_id: z.string().uuid(),
  contact_id: z.string().uuid(),
  conversation_id: z.string().uuid().optional(),
  service_type: z.enum(SERVICE_TYPES),
  requested_for: z.string().datetime().optional(), // ISO 8601
  notes: z.string().max(2000).optional(),
});

interface OutputData {
  order_id: string;
  order_number: string | null;
  status: 'draft';
  order: OrderRow;
}

/**
 * Create a fresh order in 'draft' status. No items yet — those come via
 * orders.add_item.
 *
 * Idempotency layers:
 *  1. wrapTool's tool_executions cache (returns the same envelope on replay).
 *  2. orders.UNIQUE(tenant_id, correlation_id): if cache 1 is somehow
 *     bypassed, the DB still refuses a duplicate. We exploit this with
 *     INSERT ... ON CONFLICT DO NOTHING and a follow-up SELECT for the
 *     existing row.
 *
 * order_number is auto-generated by trigger fn_set_order_number() on INSERT,
 * so we don't compute it here.
 */
export const ordersCreateDraft: ToolDefinition<typeof InputSchema, OutputData> = {
  code: 'orders.create_draft',
  moduleCode: 'orders',
  version: 'v1',
  input: InputSchema,
  async handler({ tx, ctx, input }) {
    // Verify the restaurant belongs to the tenant. RLS already filters it,
    // so a row missing here means either wrong tenant or wrong id.
    const restaurant = await tx<Array<{ id: string; status: string }>>`
      SELECT id, status FROM restaurants WHERE id = ${input.restaurant_id} LIMIT 1
    `;
    if (!restaurant[0]) {
      notFound(`Restaurant ${input.restaurant_id} not found in this tenant`);
    }
    if (restaurant[0].status !== 'active') {
      notFound(`Restaurant ${input.restaurant_id} is not active`);
    }

    // Verify the contact too.
    const contact = await tx<Array<{ id: string; status: string }>>`
      SELECT id, status FROM contacts WHERE id = ${input.contact_id} LIMIT 1
    `;
    if (!contact[0]) {
      notFound(`Contact ${input.contact_id} not found`);
    }

    // INSERT ... ON CONFLICT DO NOTHING relies on the unique
    // (tenant_id, correlation_id) index. correlation_id is NOT NULL on
    // orders so we always have a key to dedupe on.
    const inserted = await tx<Array<OrderRow>>`
      INSERT INTO orders (
        tenant_id, restaurant_id, contact_id, conversation_id,
        correlation_id, service_type, status,
        subtotal_amount, total_amount, items_count,
        currency, requested_for, notes
      )
      VALUES (
        ${ctx.tenantId}, ${input.restaurant_id}, ${input.contact_id},
        ${input.conversation_id ?? null},
        ${ctx.correlationId}, ${input.service_type}, 'draft',
        0, 0, 0,
        (SELECT currency FROM restaurants WHERE id = ${input.restaurant_id}),
        ${input.requested_for ?? null}, ${input.notes ?? null}
      )
      ON CONFLICT (tenant_id, correlation_id) DO NOTHING
      RETURNING *
    `;

    let order: OrderRow;
    if (inserted[0]) {
      order = inserted[0];
    } else {
      // Conflict on (tenant_id, correlation_id) → existing order, fetch it.
      const existing = await tx<Array<OrderRow>>`
        SELECT * FROM orders
        WHERE correlation_id = ${ctx.correlationId}
        LIMIT 1
      `;
      if (!existing[0]) {
        // Should not happen — ON CONFLICT means a row exists.
        throw new Error('orders.create_draft: ON CONFLICT but no existing row');
      }
      order = existing[0];
    }

    return ok<OutputData>({
      order_id: order.id,
      order_number: order.order_number,
      status: 'draft',
      order,
    });
  },
};
